import 'package:envied/envied.dart';

part 'env.g.dart';

/// Compile-time environment configuration generated by `envied`.
///
/// Values are read from the `.env` file at build time (see `.env.example`).
/// After changing `.env`, regenerate with:
///
/// ```sh
/// dart run build_runner build --delete-conflicting-outputs
/// ```
///
/// For multiple environments, add extra `@Envied(path: '.env.prod', name: ...)`
/// annotations and select the active class at runtime.
@Envied(path: '.env', requireEnvFile: true)
abstract final class Env {
  /// Base URL of the REST API.
  @EnviedField(varName: 'API_BASE_URL')
  static const String apiBaseUrl = _Env.apiBaseUrl;

  /// Optional API key. `obfuscate: true` encrypts the value in the generated
  /// code so it is not stored as plain text in the binary. Obfuscated fields
  /// are generated as `final` (not `const`).
  @EnviedField(varName: 'API_KEY', obfuscate: true, defaultValue: '')
  static final String apiKey = _Env.apiKey;
}
